name: DependabotAlerts

on:
  # push:
  #  branches: 
  #    - main
  workflow_dispatch:
  # schedule:
  #  - cron:  '15 * * * *'

jobs:
  slack_reporter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Report vulnerabilities to slack
        run: |
          npm ci
          echo "owner:  ${{github.repository_owner}}  repo: ${{github.event.repository.name}}"
          node reportVulsToSlack.js ${{github.repository_owner}} ${{github.event.repository.name}} ${{secrets.GH_DEPENDABOT_PAT}} ${{secrets.SLACK_WEBHOOK}}
