name: DependabotAlerts

on:
  # push:
  #  branches: 
  #    - main
  workflow_dispatch:

jobs:
  slack_reporter:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Show env
        run: env

      - name: Report vulnerabilities to slack
        run: node checkVulnerabilities.js ${{github.repository_owner}} ${{github.event.repository.name}} ${{github.token}} ${{secrets.SLACK_WEBHOOK}}
