name: DependabotAlerts

on:
  # push:
  #  branches: 
  #    - main
  workflow_dispatch:
  # schedule:
  #  - cron:  '15 * * * *'

jobs:
  slack_reporter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Report vulnerabilities to slack
        run: |
          npm ci
          # alternative for github.event.repository.name when event is not available (e.g. schedule)
          node reportVulsToSlack.js ${{github.repository_owner}} ${{github.event.repository.name}} ${{secrets.GH_DEPENDABOT_PAT}} ${{secrets.SLACK_WEBHOOK}}
